### ISSUE TITLE
Token problem

### ISSUE THREAD

**Issue by shmup** [keith/gist.vim#5]
What am I doing wrong?

I have a token, it's the same token I'm using with https://github.com/joeyespo/grip 

Cool.

So I just store the token in the password field for the `api.github.com` block in the `.netrc`? The login field wouldn't be needed at this point, but I've tried it with or without. I haven't _debugged_, so all I know is:

_Got 404, update your token to with the gist scope_ (verbatim)

I like that your plugin is light as heck on the vim side especially. I think a few things should happen:

1. That error message is confusing, but it makes me wonder if it's not reading my token at all.

2. Heck with the required description, let's make that your preferred default, but also able to be turned off (can you not POST an empty description? If not I wonder what the other, heavier, vim-gist plugins are doing)

3. Just call me an idiot if I'm being one, it's _very_ possible. Oh and my `.netrc` permissisions are `600`.

**Comment by shmup** [comment]
Yep, it was 3, I am an idiot. The "typo" in the error message made my brain stop trying and understand it meant to give the token `create gist` permissions.

:cool:

**Comment by keith** [comment]
😛 🦆
